netbox_docker_plugin/urls.py
"""URL definitions"""

from django.urls import path
from netbox.views.generic import ObjectChangeLogView, ObjectJournalView
from .models.host import Host
from .models.image import Image
from .models.volume import Volume
from .models.network import Network
from .models.container import Container
from .models.registry import Registry
from .views import (
    host as host_views,
    image as image_views,
    volume as volume_views,
    network as network_views,
    container as container_views,
    env as env_views,
    label as label_views,
    port as port_views,
    mount as mount_views,
    bind as bind_views,
    network_setting as network_setting_views,
    registry as registry_views,
    device as device_views,
    log_driver_option as log_driver_option_views
)

urlpatterns = (
    # Host
    path("hosts/", host_views.HostListView.as_view(), name="host_list"),
    path("hosts/add/", host_views.HostEditView.as_view(), name="host_add"),
    path("hosts/import/", host_views.HostBulkImportView.as_view(), name="host_import"),
    path("hosts/edit/", host_views.HostBulkEditView.as_view(), name="host_bulk_edit"),
    path(
        "hosts/delete/",
        host_views.HostBulkDeleteView.as_view(),
        name="host_bulk_delete",
    ),
    path("hosts/<int:pk>/", host_views.HostView.as_view(), name="host"),
    path("hosts/<int:pk>/edit/", host_views.HostEditView.as_view(), name="host_edit"),
    path(
        "hosts/<int:pk>/delete/",
        host_views.HostDeleteView.as_view(),
        name="host_delete",
    ),
    path(
        "hosts/<int:pk>/operation/<str:operation>/",
        host_views.HostOperationView.as_view(),
        name="host_operation",
    ),
    path(
        "hosts/<int:pk>/graph/",
        host_views.HostGraphView.as_view(),
        name="host_graph",
    ),
    path(
        "hosts/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="host_changelog",
        kwargs={"model": Host},
    ),
    path(
        "hosts/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="host_journal",
        kwargs={"model": Host},
    ),
    # Image
    path("images/", image_views.ImageListView.as_view(), name="image_list"),
    path("images/add/", image_views.ImageEditView.as_view(), name="image_add"),
    path(
        "images/import/", image_views.ImageBulkImportView.as_view(), name="image_import"
    ),
    path(
        "images/edit/", image_views.ImageBulkEditView.as_view(), name="image_bulk_edit"
    ),
    path(
        "images/delete/",
        image_views.ImageBulkDeleteView.as_view(),
        name="image_bulk_delete",
    ),
    path("images/<int:pk>/", image_views.ImageView.as_view(), name="image"),
    path(
        "images/<int:pk>/edit/", image_views.ImageEditView.as_view(), name="image_edit"
    ),
    path(
        "images/<int:pk>/delete/",
        image_views.ImageDeleteView.as_view(),
        name="image_delete",
    ),
    path(
        "images/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="image_changelog",
        kwargs={"model": Image},
    ),
    path(
        "images/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="image_journal",
        kwargs={"model": Image},
    ),
    # Volume
    path("volumes/", volume_views.VolumeListView.as_view(), name="volume_list"),
    path("volumes/add/", volume_views.VolumeEditView.as_view(), name="volume_add"),
    path(
        "volumes/import/",
        volume_views.VolumeBulkImportView.as_view(),
        name="volume_import",
    ),
    path(
        "volumes/delete/",
        volume_views.VolumeBulkDeleteView.as_view(),
        name="volume_bulk_delete",
    ),
    path("volumes/<int:pk>/", volume_views.VolumeView.as_view(), name="volume"),
    path(
        "volumes/<int:pk>/edit/",
        volume_views.VolumeEditView.as_view(),
        name="volume_edit",
    ),
    path(
        "volumes/<int:pk>/delete/",
        volume_views.VolumeDeleteView.as_view(),
        name="volume_delete",
    ),
    path(
        "volumes/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="volume_changelog",
        kwargs={"model": Volume},
    ),
    path(
        "volumes/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="volume_journal",
        kwargs={"model": Volume},
    ),
    # Network
    path("networks/", network_views.NetworkListView.as_view(), name="network_list"),
    path("networks/add/", network_views.NetworkEditView.as_view(), name="network_add"),
    path(
        "networks/import/",
        network_views.NetworkBulkImportView.as_view(),
        name="network_import",
    ),
    path(
        "networks/edit/",
        network_views.NetworkBulkEditView.as_view(),
        name="network_bulk_edit",
    ),
    path(
        "networks/delete/",
        network_views.NetworkBulkDeleteView.as_view(),
        name="network_bulk_delete",
    ),
    path("networks/<int:pk>/", network_views.NetworkView.as_view(), name="network"),
    path(
        "networks/<int:pk>/edit/",
        network_views.NetworkEditView.as_view(),
        name="network_edit",
    ),
    path(
        "networks/<int:pk>/delete/",
        network_views.NetworkDeleteView.as_view(),
        name="network_delete",
    ),
    path(
        "networks/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="network_changelog",
        kwargs={"model": Network},
    ),
    path(
        "networks/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="network_journal",
        kwargs={"model": Network},
    ),
    # Container
    path(
        "containers/",
        container_views.ContainerListView.as_view(),
        name="container_list",
    ),
    path(
        "containers/add/",
        container_views.ContainerNewView.as_view(),
        name="container_add",
    ),
    path(
        "containers/import/",
        container_views.ContainerBulkImportView.as_view(),
        name="container_import",
    ),
    path(
        "containers/edit/",
        container_views.ContainerBulkEditView.as_view(),
        name="container_bulk_edit",
    ),
    path(
        "containers/delete/",
        container_views.ContainerBulkDeleteView.as_view(),
        name="container_bulk_delete",
    ),
    path(
        "containers/<int:pk>/",
        container_views.ContainerView.as_view(),
        name="container",
    ),
    path(
        "containers/<int:pk>/logs",
        container_views.ContainerLogsView.as_view(),
        name="container_logs",
    ),
    path(
        "containers/<int:pk>/exec",
        container_views.ContainerExecView.as_view(),
        name="container_exec",
    ),
    path(
        "containers/<int:pk>/edit/",
        container_views.ContainerEditView.as_view(),
        name="container_edit",
    ),
    path(
        "containers/<int:pk>/delete/",
        container_views.ContainerDeleteView.as_view(),
        name="container_delete",
    ),
    path(
        "containers/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="container_changelog",
        kwargs={"model": Container},
    ),
    path(
        "containers/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="container_journal",
        kwargs={"model": Container},
    ),
    path(
        "containers/<int:pk>/operation/<str:operation>/",
        container_views.ContainerOperationView.as_view(),
        name="container_operation",
    ),
    # Env
    path(
        "env/",
        env_views.EnvListView.as_view(),
        name="env_list",
    ),
    path(
        "env/add/",
        env_views.EnvEditView.as_view(),
        name="env_add",
    ),
    path(
        "env/<int:pk>/edit/",
        env_views.EnvEditView.as_view(),
        name="env_edit",
    ),
    path(
        "env/<int:pk>/delete/",
        env_views.EnvDeleteView.as_view(),
        name="env_delete",
    ),
    # Log Driver Option
    path(
        "log-driver-options/",
        log_driver_option_views.LogDriverOptionListView.as_view(),
        name="logdriveroption_list",
    ),
    path(
        "log-driver-options/add/",
        log_driver_option_views.LogDriverOptionEditView.as_view(),
        name="logdriveroption_add",
    ),
    path(
        "log-driver-options/<int:pk>/edit/",
        log_driver_option_views.LogDriverOptionEditView.as_view(),
        name="logdriveroption_edit",
    ),
    path(
        "log-driver-options/<int:pk>/delete/",
        log_driver_option_views.LogDriverOptionDeleteView.as_view(),
        name="logdriveroption_delete",
    ),
    # Label
    path(
        "labels/",
        label_views.LabelListView.as_view(),
        name="label_list",
    ),
    path(
        "labels/add/",
        label_views.LabelEditView.as_view(),
        name="label_add",
    ),
    path(
        "labels/<int:pk>/edit/",
        label_views.LabelEditView.as_view(),
        name="label_edit",
    ),
    path(
        "labels/<int:pk>/delete/",
        label_views.LabelDeleteView.as_view(),
        name="label_delete",
    ),
    # Port
    path(
        "ports/",
        port_views.PortListView.as_view(),
        name="port_list",
    ),
    path(
        "ports/add/",
        port_views.PortEditView.as_view(),
        name="port_add",
    ),
    path(
        "ports/<int:pk>/edit/",
        port_views.PortEditView.as_view(),
        name="port_edit",
    ),
    path(
        "ports/<int:pk>/delete/",
        port_views.PortDeleteView.as_view(),
        name="port_delete",
    ),
    # Mount
    path(
        "mounts/",
        mount_views.MountListView.as_view(),
        name="mount_list",
    ),
    path(
        "mounts/add/",
        mount_views.MountEditView.as_view(),
        name="mount_add",
    ),
    path(
        "mounts/<int:pk>/edit/",
        mount_views.MountEditView.as_view(),
        name="mount_edit",
    ),
    path(
        "mounts/<int:pk>/delete/",
        mount_views.MountDeleteView.as_view(),
        name="mount_delete",

netbox_docker_plugin/models/host.py
"""Host Models definitions"""

from django.db import models
from django.urls import reverse
from django.core.validators import (
    URLValidator,
    MinLengthValidator,
    MaxLengthValidator,
)
from utilities.choices import ChoiceSet
from users.models import Token
from netbox.models import NetBoxModel


class HostStateChoices(ChoiceSet):
    """Host state choices definition class"""

    key = "Host.state"

    STATE_CREATED = "created"
    STATE_DELETED = "deleted"
    STATE_RUNNING = "running"
    STATE_REFRESHING = "refreshing"

    CHOICES = [
        (STATE_CREATED, "Created", "dark"),
        (STATE_RUNNING, "Running", "blue"),
        (STATE_DELETED, "Deleted", "blue"),
        (STATE_REFRESHING, "Refreshing", "blue"),
    ]


class HostOperationChoices(ChoiceSet):
    """Host operation choices definition class"""

    key = "Host.operation"

    OPERATION_REFRESH = "refresh"
    OPERATION_NONE = "none"

    CHOICES = [
        (OPERATION_REFRESH, "Refresh", "blue"),
        (OPERATION_NONE, "None", "white"),
    ]


class Host(NetBoxModel):
    """Host definition class"""

    endpoint = models.CharField(max_length=1024, validators=[URLValidator()])
    name = models.CharField(
        unique=True,
        max_length=255,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )
    state = models.CharField(
        max_length=32,
        choices=HostStateChoices,
        default=HostStateChoices.STATE_CREATED,
    )
    token = models.ForeignKey(Token, on_delete=models.SET_NULL, null=True, blank=True)
    netbox_base_url = models.CharField(
        max_length=1024,
        validators=[URLValidator()],
        null=True,
        blank=True,
    )
    agent_version = models.CharField(
        max_length=32,
        null=True,
        blank=True,
    )
    docker_api_version = models.CharField(
        max_length=32,
        null=True,
        blank=True,
    )
    operation = models.CharField(
        max_length=32,
        choices=HostOperationChoices,
        default=HostOperationChoices.OPERATION_NONE,
    )

    class Meta:
        """Host Model Meta Class"""

        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_docker_plugin:host", args=[self.pk])

    def delete(self, using=None, keep_parents=False):
        self.state = HostStateChoices.STATE_DELETED
        self.save()

        return super().delete(using, keep_parents)

    def save(
        self, *args, **kwargs
    ):
        if self.operation == HostOperationChoices.OPERATION_REFRESH:
            self.state = HostStateChoices.STATE_REFRESHING

        return super().save(*args, **kwargs)

netbox_docker_plugin/models/image.py
from django.db import models
from django.urls import reverse
from django.core.validators import (
    MinLengthValidator,
    MaxLengthValidator,
    MinValueValidator,
    MaxValueValidator,
)
from django.contrib.auth.models import User  # Importation du modèle User
from netbox.models import NetBoxModel
from .host import Host
from .registry import Registry


class Image(NetBoxModel):
    """Image definition class"""

    host = models.ForeignKey(Host, on_delete=models.CASCADE, related_name="images")
    registry = models.ForeignKey(
        Registry,
        on_delete=models.CASCADE,
        related_name="images",
    )
    user = models.ForeignKey(
        User,  # Ajout de la clé étrangère vers le modèle User
        on_delete=models.CASCADE,
        related_name="images",  # Vous pouvez ajuster le related_name si nécessaire
        null=True,  # Permettre à l'image de ne pas avoir d'utilisateur
        blank=True,  # Permettre à l'image de ne pas avoir d'utilisateur
    )
    name = models.CharField(
        max_length=255,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )
    version = models.CharField(
        default="latest",
        max_length=256,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=256),
        ],
    )
    size = models.IntegerField(
        default=0,
        validators=[
            MinValueValidator(limit_value=0),
            MaxValueValidator(limit_value=4096),
        ],
    )
    ImageID = models.CharField(
        max_length=128,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=128),
        ],
        default=None,
        blank=True,
        null=True,
    )
    Digest = models.CharField(
        max_length=512,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=512),
        ],
        default=None,
        blank=True,
        null=True,
    )

    class Meta:
        """Image Model Meta Class"""

        ordering = ("name", "version")
        constraints = (
            models.UniqueConstraint(
                fields=["host", "registry", "name", "version"],
                name="%(app_label)s_%(class)s_unique_version_name_registry_host",
            ),
            models.UniqueConstraint(
                fields=["host", "ImageID"],
                name="%(app_label)s_%(class)s_unique_ImageID_host",
            ),
        )

    def __str__(self):
        return f"{self.name}:{self.version}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_docker_plugin:image", args=[self.pk])

netbox_docker_plugin/models/registry.py
"""Registry Model definition"""

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import (
    MinLengthValidator,
    MaxLengthValidator,
)
from django.urls import reverse
from netbox.models import NetBoxModel
from .host import Host


@receiver(post_save, sender=Host)
def create_default_registry(sender, **kwargs): # pylint: disable=W0613
    """Create default registry on Host creation"""

    if kwargs.get("created") is True:
        registry = Registry(
            host=kwargs.get("instance"),
            name="dockerhub",
            serveraddress="https://registry.hub.docker.com/v2/",
        )
        registry.save()


class Registry(NetBoxModel):
    """Registry definition class"""

    host = models.ForeignKey(Host, on_delete=models.CASCADE, related_name="registries")
    name = models.CharField(
        max_length=255,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )
    serveraddress = models.URLField()
    username = models.CharField(blank=True, null=True, max_length=512)
    password = models.CharField(blank=True, null=True, max_length=512)
    email = models.EmailField(blank=True, null=True, max_length=512)

    class Meta:
        """Registry Model Meta Class"""

        ordering = ("name",)
        constraints = (
            models.UniqueConstraint(
                fields=["host", "name"],
                name="%(app_label)s_%(class)s_name_host",
            ),
        )

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_docker_plugin:registry", args=[self.pk])

netbox_docker_plugin/templates/netbox_docker_plugin/container-detail.html
{% extends "netbox_docker_plugin/container-layout.html" %}

{% load plugins %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">CONTAINER</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Host</th>
            <td><a href="{{ object.host.get_absolute_url }}">{{ object.host }}</a></td>
          </tr>
          <tr>
            <th scope="row">Image</th>
            <td><a href="{{ object.image.get_absolute_url }}">{{ object.image }}</a></td>
          </tr>
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">ContainerID</th>
            <td>{{ object.ContainerID|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Hostname</th>
            <td>{{ object.hostname|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">State</th>
            <td>{{ object.get_state_display }}</td>
          </tr>
          <tr>
            <th scope="row">Restart Policy</th>
            <td>{{ object.get_restart_policy_display }}</td>
          </tr>
          <tr>
            <th scope="row">Status</th>
            <td>{{ object.status|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Operation</th>
            <td>{{ object.get_operation_display }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">PORT MAPPINGS</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:port_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_env %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:port_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Port Mapping
          </a>
        </div>
      {% endif %}
    </div>
    <div class="card">
      <h5 class="card-header">MOUNTS</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:mount_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_env %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:mount_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> New Mount
          </a>
        </div>
      {% endif %}
    </div>
    <div class="card">
      <h5 class="card-header">BINDS</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:bind_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_env %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:bind_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> New Bind
          </a>
        </div>
      {% endif %}
    </div>
    <div class="card">
      <h5 class="card-header">NETWORK SETTINGS</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:networksetting_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_network_setting %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:networksetting_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> New Network Setting
          </a>
        </div>
      {% endif %}
    </div>
    <div class="card">
      <h5 class="card-header">ENV VARIABLE</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:env_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_env %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:env_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add an Env Variable
          </a>
        </div>
      {% endif %}
    </div>
    <div class="card">
      <h5 class="card-header">LABELS</h5>
      <div class="card-body htmx-container table-responsive"
        hx-get="{% url 'plugins:netbox_docker_plugin:label_list' %}?container_id={{ object.pk }}"
        hx-trigger="load"
      ></div>
      {% if perms.netbox_docker_plugin.add_env %}
        <div class="card-footer text-end noprint">
          <a href="{% url 'plugins:netbox_docker_plugin:label_add' %}?container={{ object.pk }}&return_url={{ object.get_absolute_url }}" class="btn btn-primary btn-sm">
            <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Label
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

netbox_docker_plugin/templates/netbox_docker_plugin/host.html
{% extends 'generic/object.html' %}

{% load plugins %}
{% load host %}

{% block extra_controls %}
<form action="{% url 'plugins:netbox_docker_plugin:host_operation' pk=object.id operation='refresh' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="operation" value="refresh">
  <button type="submit" class="btn btn-warning">
    <i class="mdi mdi-cog-refresh"></i> Refresh
  </button>
</form>
{% endblock extra_controls %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h2 class="card-header">Host</h2>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">Name</th>
          <td>{{ object.name }}</td>
        </tr>
        <tr>
          <th scope="row">Endpoint</th>
          <td>{{ object.endpoint|remove_password }}</td>
        </tr>
        <tr>
          <th scope="row">State</th>
          <td>{{ object.get_state_display }}</td>
        </tr>
        <tr>
          <th scope="row">Agent Version</th>
          <td>{{ object.agent_version|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Docker API Version</th>
          <td>{{ object.docker_api_version|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Operation</th>
          <td>{{ object.get_operation_display }}</td>
        </tr>
      </table>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
  <div class="col col-md-6">
    {% include 'inc/panels/related_objects.html' with filter_name='host_id' %}
    {% plugin_right_page object %}
  </div>
</div>
<div class="row">
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        Registry
        {% if perms.netbox_docker_plugin.add_container %}
          <div class="card-actions">
            <a href="{% url 'plugins:netbox_docker_plugin:registry_add' %}?host={{ object.pk }}&return_url={{ object.get_absolute_url }}"
              class="btn btn-ghost-primary btn-sm">
              <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Registry
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'plugins:netbox_docker_plugin:registry_list' host_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        Container
        {% if perms.netbox_docker_plugin.add_container %}
          <div class="card-actions">
            <a href="{% url 'plugins:netbox_docker_plugin:container_add' %}?host={{ object.pk }}&return_url={{ object.get_absolute_url }}"
              class="btn btn-ghost-primary btn-sm">
              <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Container
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'plugins:netbox_docker_plugin:container_list' host_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        Images
        {% if perms.netbox_docker_plugin.add_image %}
          <div class="card-actions">
            <a href="{% url 'plugins:netbox_docker_plugin:image_add' %}?host={{ object.pk }}&return_url={{ object.get_absolute_url }}"
              class="btn btn-ghost-primary btn-sm">
              <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add an Image
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'plugins:netbox_docker_plugin:image_list' host_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        Volumes
        {% if perms.netbox_docker_plugin.add_volume %}
          <div class="card-actions">
            <a href="{% url 'plugins:netbox_docker_plugin:volume_add' %}?host={{ object.pk }}&return_url={{ object.get_absolute_url }}"
              class="btn btn-ghost-primary btn-sm">
              <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Volume
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'plugins:netbox_docker_plugin:volume_list' host_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        Networks
        {% if perms.netbox_docker_plugin.add_network %}
          <div class="card-actions">
            <a href="{% url 'plugins:netbox_docker_plugin:network_add' %}?host={{ object.pk }}&return_url={{ object.get_absolute_url }}"
              class="btn btn-ghost-primary btn-sm">
              <i class="mdi mdi-plus-thick" aria-hidden="true"></i> Add a Network
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'plugins:netbox_docker_plugin:network_list' host_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
</div>
{% endblock content %}